<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>
<?php foreach ($values as $term => $propertyData): ?>
    <?php
        if ($propertyData['alternate_label']) {
            $propLabel = $escape($propertyData['alternate_label']);
        } else {
            $propLabel = $escape($translate($propertyData['property']->label()));
        }

        $propLabelClass = preg_replace('/\s+/', '-', mb_strtolower($propLabel));

        if ('term' === $labelInfo) {
            $propLabelMeta = $escape($propertyData['property']->term());
        } elseif ('vocab' === $labelInfo) {
            $propLabelMeta = $escape($propertyData['property']->vocabulary()->label());
        } else {
            $propLabelMeta = null;
        }
    ?>

    <div class="property <?php echo $propLabelClass ?>">
        <h4>
        <?php echo $propLabel; ?>
        <?php if ($propLabelMeta): ?>
        <span class="field-term">(<?php echo $propLabelMeta; ?>)</span>
        <?php endif; ?>
        </h4>
        <div class="values">
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            $valueType = $value->type();
            $class = ['value'];
            if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            ?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php echo $value->asHtml(); ?>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
